### ISSUE TITLE
running locally with back4app giving error

### ISSUE THREAD

**Issue by johhansantana** [beachio/chisel#8]
after running the `chisel-cms` command and pointing to my app at back4app I get an `unauthorized` error:

![image](https://user-images.githubusercontent.com/9933887/50541576-2ae65100-0b7f-11e9-93ae-1f80fdcb68a9.png)

**Comment by r3trosteve** [comment]
Unfortunately Chisel isn’t compatible with other 3rd party parse-server hosts at present, since Chisel requires certain handling of emails and other modules that these providers may not support. There’s also some features which require some cloud code functions.

You should check out our parse-server starter project https://github.com/beachio/chisel-parse-server-starter

**Comment by johhansantana** [comment]
Alright I will. Thanks!
